//! Public, independently published standard-chess perft acceptance vectors.
//!
//! Source: https://www.chessprogramming.org/Perft_Results. Golden counts are
//! fixed fixture data rather than expectations generated by the engine itself.

use rz_position::Position;

fn cases() -> impl Iterator<Item = (&'static str, &'static str, Vec<u64>)> {
    include_str!("fixtures/perft.tsv")
        .lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| {
            let mut fields = line.split('\t');
            let name = fields.next().unwrap();
            let fen = fields.next().unwrap();
            let counts = fields.map(|field| field.parse().unwrap()).collect();
            (name, fen, counts)
        })
}

fn check(name: &str, fen: &str, depth: u32, expected: u64) {
    let position = Position::from_fen(fen)
        .unwrap_or_else(|error| panic!("fixture={name}; FEN={fen}; parse: {error:?}"));
    let actual = position
        .perft(depth)
        .unwrap_or_else(|error| panic!("fixture={name}; FEN={fen}; depth={depth}: {error:?}"));
    if actual != expected {
        let divide = position
            .divide(depth)
            .unwrap()
            .into_iter()
            .map(|(mv, nodes)| format!("{mv}: {nodes}"))
            .collect::<Vec<_>>()
            .join(", ");
        panic!(
            "fixture={name}; FEN={fen}; depth={depth}; expected={expected}; actual={actual}; \
             divide={divide}; compare the first differing root path with the pinned oracle"
        );
    }
    assert_eq!(position.to_fen(), fen, "perft modified fixture={name}");
}

#[test]
fn public_perft_suite() {
    for (name, fen, counts) in cases() {
        for (index, expected) in counts.iter().take(3).enumerate() {
            check(name, fen, index as u32 + 1, *expected);
        }
        // Two low-cost deeper vectors cover pawn double pushes and EP endgames.
        if name == "startpos" || name == "cpw_ep_endgame" {
            check(name, fen, 4, counts[3]);
        }
    }
}

#[test]
#[ignore = "extended bounded perft suite; run explicitly in release mode"]
fn public_perft_depth_four() {
    for (name, fen, counts) in cases() {
        check(name, fen, 4, counts[3]);
    }
}

#[test]
fn published_startpos_divide_depth_three() {
    // CPW initial-position depth-three divide, sorted by UCI for diagnostics.
    let expected = [
        ("a2a3", 380),
        ("a2a4", 420),
        ("b1a3", 400),
        ("b1c3", 440),
        ("b2b3", 420),
        ("b2b4", 421),
        ("c2c3", 420),
        ("c2c4", 441),
        ("d2d3", 539),
        ("d2d4", 560),
        ("e2e3", 599),
        ("e2e4", 600),
        ("f2f3", 380),
        ("f2f4", 401),
        ("g1f3", 440),
        ("g1h3", 400),
        ("g2g3", 420),
        ("g2g4", 421),
        ("h2h3", 380),
        ("h2h4", 420),
    ];
    let position = Position::startpos();
    let initial_fen = position.to_fen();
    let mut actual = position
        .divide(3)
        .unwrap()
        .into_iter()
        .map(|(mv, nodes)| (mv.to_string(), nodes))
        .collect::<Vec<_>>();
    actual.sort();
    assert_eq!(
        actual.len(),
        expected.len(),
        "FEN={initial_fen}; root moves"
    );
    for ((mv, nodes), (expected_move, expected_nodes)) in actual.iter().zip(expected) {
        assert_eq!(mv, expected_move, "FEN={initial_fen}; first root move");
        assert_eq!(
            *nodes, expected_nodes,
            "FEN={initial_fen}; depth=3; first differing path={mv}"
        );
    }
    assert_eq!(position.to_fen(), initial_fen, "divide changed state");
}
